package com.lina.pengenalanpakaianadatnusantaran;

import androidx.appcompat.app.AppCompatActivity;
import androidx.cardview.widget.CardView;
import androidx.viewpager.widget.ViewPager;

import android.animation.ArgbEvaluator;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;

import java.util.ArrayList;
import java.util.List;

public class MateriPakaianAdatActivity extends AppCompatActivity {

    ViewPager viewPager;
    AdapterPakaianAdat adapter;
    List<PakaianAdatModel> models;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_materi_pakaian_adat);

        models = new ArrayList<>();
        models.add(new PakaianAdatModel(R.drawable.bali, "Bali", "Pakaian adat sehari - hari Bali", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.dki_jakarta, "DKI Jakarta", "Pakaian adat sehari - hari Jakarta", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.banten_pria, "Banten Pria", "Pakaian adat sehari - hari Banten Pria", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.banten_wanita, "Banten Wanita", "Pakaian adat sehari - hari Banten Wanita", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.d_i_yogyakarta, "D I Yogyakarta", "Pakaian adat sehari - hari D I Yogyakarta", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.jawa_barat, "Jawa Barat", "Pakaian adat sehari - hari Barat", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.jawa_tengah, "Jawa Tengah", "Pakaian adat sehari - hari Tengah", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.jawa_timur_banyuwangi, "Jawa Timur Banyuwangi", "Pakaian adat sehari - hari Jawa Timur Banyuwangi", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.jawa_timur_madura, "Jawa Timur Madura", "Pakaian adat sehari - hari Jawa Timur Madura", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.kalimantan_barat_pria, "Kalimantan Barat Pria", "Pakaian adat sehari - hari Kalimantan Barat Pria", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.kalimantan_barat_wanita, "Kalimantan Barat Wanita", "Pakaian adat sehari - hari Kalimantan Barat Wanita", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.kalimantan_tengah, "Kalimantan Tengah", "Pakaian adat sehari - hari Kalimantan Tengah", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.kalimantan_utara, "Kalimantan Utara", "Pakaian adat sehari - hari Kalimantan Utara", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.lampung_pria, "Lampung Pria", "Pakaian adat sehari - hari Lampung Pria", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.lampung_wanita, "Lampung Wanita", "Pakaian adat sehari - hari Lampung Wanita", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.ntt_suku_manggarai_sikka, "Nusa Tenggara  Timur Suku Manggarai & Sikka", "Pakaian adat sehari - hari Nusa Tenggara  Timur Suku Manggarai & Sikka", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.ntb_suku_bima, "Nusa Tenggara Barat Suku Bima", "Pakaian adat sehari - hari Nusa Tenggara Timur Suku Bima", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.ntt_suku_sumba, "Nusa Tenggara Timur Suku Sumba", "Pakaian adat sehari - hari Nusa Tenggara Timur Suku Sumba", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));
        models.add(new PakaianAdatModel(R.drawable.ntt_suku_timor_barat_bajawan, "Nusa Tenggara Timur Suku Timor Barat & Bajawa", "Pakaian adat sehari - hari Nusa Tenggara Timur Suku Timor Barat & Bajawa", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lectus lectus, molestie non nunc aliquam, elementum interdum lacus. Vivamus pellentesque gravida magna id ullamcorper. Quisque non faucibus nisl, ut luctus sapien. Praesent in elementum felis. Quisque hendrerit nisi eget condimentum maximus. Nullam sed augue at sem egestas feugiat at id turpis. Pellentesque convallis id ipsum et interdum. In sed luctus neque.\n" +
                "\n" +
                "Curabitur ut quam magna. Phasellus euismod ultrices mauris, quis venenatis leo auctor aliquet. Curabitur sed ante libero. Fusce sagittis tincidunt blandit. Donec cursus vehicula tortor non ultricies. Proin eget magna sit amet libero lobortis iaculis sit amet vitae ex. Vivamus ut iaculis elit. Proin lorem erat, ultricies nec molestie eget, bibendum in urna. Donec felis erat, commodo nec mi ut, dignissim mollis magna. Fusce volutpat ac ipsum a semper. Vivamus dignissim iaculis volutpat."));

        adapter = new AdapterPakaianAdat(models, this);

        viewPager = findViewById(R.id.viewPager);
        viewPager.setAdapter(adapter);
        viewPager.setPadding(130, 0, 130, 0);

        ImageView imageBackIcon = findViewById(R.id.back_icon);
        imageBackIcon.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(MateriPakaianAdatActivity.this, KategoriMateriActivity.class);
                intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                startActivity(intent);
            }
        });
    }
}
